openapi: 3.0.3
info:
  title: Task Control System API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /users/v1/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string, minLength: 6 }
                name: { type: string }
      responses:
        '201':
          description: Created
  /users/v1/login:
    post:
      summary: Login and get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string, minLength: 6 }
      responses:
        '200':
          description: OK
  /users/v1/profile:
    get:
      summary: Get current profile
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: OK }
    patch:
      summary: Update current profile
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: OK }
  /users/v1/users:
    get:
      summary: Admin list users
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: OK }
  /orders/v1/orders:
    post:
      summary: Create order
      security: [{ bearerAuth: [] }]
      responses:
        '201': { description: Created }
    get:
      summary: List my orders
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: OK }
  /orders/v1/orders/{id}:
    get:
      summary: Get order by id
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    patch:
      summary: Update order status
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    delete:
      summary: Cancel order (owner only)
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
